# This is a deploy workflow to test server

name: CI Build

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      id: build_task
      run: npm run build --if-present
    - name: Archive dist
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
        retention-days: 1
