# This is a deploy workflow to test server

name: CI Publish Dev

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger bump-version in townsquare
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: townteki
          repo: townsquare
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user: ${{ secrets.GITHUB_ACTOR }}
          workflow_file_name: test.yml
          ref: bumpversion
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
  call-workflow-build:
    uses: townteki/townsquare-client/.github/workflows/build.yml@version-bumping
    needs: bump-version
#  call-workflow-deploy:
#    uses: townteki/townsquare-client/.github/workflows/deploy-dev.yml@master
#    needs: call-workflow-build
