# This is a workflow to restart the production server

name: Restart Prod Server

on:
  workflow_dispatch:

jobs:    
  server-restart:
    runs-on: ubuntu-latest
    steps:    
    - name: Restart pm2 processes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_PROD_HOST }}
        username: ${{ secrets.REMOTE_PROD_USER }}
        key: ${{ secrets.PROD_SERVER_SSH_KEY }}
        script: |
          pm2 restart 0
          pm2 restart 1
